id: PBCFFF7D9
initial_creation_type: input
source_metadata:
  title: Dudjom Lingpa Series
  language: bo
  description: 'We present the following texts by and about the great tertön Dudjom
    Lingpa (bdud ''joms gling pa, 1835–1904):'
  volume:
    cd4fc85f752c42f686b666121c4b16db:
      title: A Sukhāvatī Prayer and Aspiration
      parent: Aspiration Prayers
    86bb57ead818482bac42f0f8d8a4e478:
      title: An Aspiration
      parent: Aspiration Prayers
    2d902ea5ede943e69cff05f3a4afcd65:
      title: An Aspiration Prayer
      parent: Aspiration Prayers
    31cfac04f536480e98c81e5a6917620a:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Biography
    18f7033427ab495ba80b6a3cb5f70548:
      title: Golden Drink (Serkyem) and Torma Offering
      parent: Offering
    42c0e4e21ff84feca5e8335682ba52c0:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Offering
    fd38d30f92644ec897a91f9b7c42926a:
      title: A Prayer
      parent: Prayers
    421c0b27ee674c72bf91bde4d1d295a1:
      title: A Prayer to Dudjom Lingpa
      parent: Prayers
    ca849edd21dd468d8d042f4cc2fbf402:
      title: A Prayer to Padmasambhava
      parent: Prayers
    a7731747f5b540b89d22a12d3ea3e9cd:
      title: A Prayer to Parṇaśavarī
      parent: Prayers
    75951eefba384528b6c008e91b2d8209:
      title: The Outer, Inner and Secret Refuge Prayer
      parent: Refuge
    7cf1855791c845959a0230f3d3a0968e:
      title: 'Making Great Bliss the Path: Visualisation and Mantra Recitation of
        Medicine Buddha'
      parent: Sādhanas
    42c755f510634b74ab2e8c858470a142:
      title: Visualization and Mantra Recitation of the Great Compassionate One
      parent: Sādhanas
created_at: '2022-02-28T23:06:52.946499'
last_modified_at: '2022-02-28T23:06:52.946502'
